---
title: "functions"
author: "Xiao Shi"
date: "October 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
```

```{r}
z_scores = function(x) {
  (x - mean(x)) / sd(x)
}
y = runif(100)
z_scores(y)
```

put in some checks on inputs
```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  z
}
```

now we run these (should be all errors)
```{r, error = TRUE}
z_scores(3)

z_scores("my name is jeff")

z_scores(iris)

z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```

mean and sd function
```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, sd = sd_x)
}
mean_and_sd(runif(100))
```

